### ISSUE TITLE
Matching algorithm

### ISSUE THREAD

**Issue by Mrmoods** [GreatBritishHackOff/BrexitRealityCheck#2]
We need a way to compare someone's set of responses to the questions with:

1. predicted responses from a selected set of MPs who are prominent in the Brexit debate
2. predicted outcomes in the cases of a no deal hard Brexit / soft Brexit / remain

A percentage match against each of these would be nice, plus the ability to see on which questions the respondent deviates from each of the MPs and Brexit outcomes.

**Comment by aspiers** [comment]
Very simple prototype: https://docs.google.com/spreadsheets/d/1bW5au1MffWOo_xmgOEo9acFGyU6PlrYtEtQyu10Rty4/edit?usp=sharing

**Comment by EtharAlali** [comment]
@aspiers Useful start. How did you get the data?

Just throwing this out there, but once matched, you can also use multinomial logistic regression for this. Also, what I probably would have done is go the other way. 

1. Create a correlation matrix between the senior figure respondents and the outcomes of each Brexit type

2. Those with very high correlations (70% upwards, especially 90% upwards) can be considered factors. 

3. Recreate the Brexit outcomes using a linear equation of coefficients against each of those polynomials - you can start with the correlation coefficient as a baseline and refine. Either through Champion Challenger or Bayes. 

4. Solve that linear equation against the original distributions (it's linear algebra) from the factors and each specific coefficient 

It's basically a factor analysis. Which even the Multilevel Regression and Post-Stratification that CA used is simply a sibling application of. 

I'm sure you've done this before, but if not, a quick and lazy google'd intro is here :)

https://www.theanalysisfactor.com/factor-analysis-1-introduction/

**Comment by aspiers** [comment]
This issue was moved to GreatBritishHackOff/Brexometer#3

**Comment by aspiers** [comment]
Hi @EtharAlali,

Firstly sorry for ignoring your very helpful message for so long ...

[**@EtharAlali**](https://github.com/EtharAlali) commented on [22 Jul 2018, 19:39 BST](https://github.com/GreatBritishHackOff/BrexitRealityCheck/issues/2#issuecomment-406887523 "2018-07-22T18:39:28Z - Replied by Github Reply Comments"):
> @aspiers Useful start. How did you get the data?

It was pure fiction, just made up to illustrate the mechanism :-)

> Just throwing this out there, but once matched, you can also use multinomial logistic regression for this. Also, what I probably would have done is go the other way. 
> 
> 1. Create a correlation matrix between the senior figure respondents and the outcomes of each Brexit type
> 
> 2. Those with very high correlations (70% upwards, especially 90% upwards) can be considered factors. 
> 
> 3. Recreate the Brexit outcomes using a linear equation of coefficients against each of those polynomials - you can start with the correlation coefficient as a baseline and refine. Either through Champion Challenger or Bayes. 
> 
> 4. Solve that linear equation against the original distributions (it's linear algebra) from the factors and each specific coefficient 
> 
> It's basically a factor analysis. Which even the Multilevel Regression and Post-Stratification that CA used is simply a sibling application of. 

Interesting - I have recently studied MRP but didn't realise that CA used it.

> I'm sure you've done this before, but if not, a quick and lazy google'd intro is here :)
> 
> https://www.theanalysisfactor.com/factor-analysis-1-introduction/

This is extremely interesting, and something I'd like to revisit when we get the app in a more mature state.  (For now I just need to launch the simplest thing which could possibly work.)  It's 25 years since my maths degree, so most of this is so rusty it's basically immobile ;-)  But maybe I can get something going later on - at which point might you be available for a chat?

**Comment by EtharAlali** [comment]
@aspiers sure man, no worries. I'll be down south a few times over the next couple of months anyway. So could even hack around this when I'm about.

**Comment by aspiers** [comment]
@EtharAlali cool thanks a lot and let me know when you're likely to be around!  BTW we have a hackathon for the next three days.  Please visit https://join.techforuk.com/ to stay in the loop!
